<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="itext7" Version="8.0.5" />
	<PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContractLib\ContractLib.csproj" />
  </ItemGroup>

	<Target Name="CopyToRPlugins" AfterTargets="Build">
		<Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
			  DestinationFiles="$(SolutionDir)FormComponentDisplay\bin\Debug\net9.0-windows\RPlugins\$(AssemblyName).dll" />
	</Target>

</Project>
